application: meh-notifier
version: 0-0-1
runtime: jruby
resource_files:
  - exclude: '/features/**'
  - exclude: '/spec/**'
  - exclude: '/live_tests/**'
  - exclude: 'README.markdown'
handlers:
  - url: /tasks/*
    login: admin
  - url: /cron/*
    login: admin
  - url: /paypal_ipns
    secure: always
  - url: /incoming_text_messages
    secure: always
  - url: /text_message_delivery_receipts
    secure: always
  - url: /tropo_messages
    secure: always
context_params:
  rack.env: production

